services:
  db:
    image: postgres:17
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgres
    env_file:
      - .env
    labels:
      service-role: "database"
    networks:
      - app_network

  backend:
    container_name: conduit-backend
    restart: unless-stopped
    build:
      context: ./conduit-backend
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}

      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}

      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS}

    env_file:
      - .env
    volumes:
      - ./logs/django:/app/logs 
    labels:
      service-role: "backend"
    networks:
      - app_network

  frontend:
    container_name: conduit-frontend
    restart: unless-stopped
    build:
      context: ./conduit-frontend
      dockerfile: frontend.Dockerfile
    ports:
      - "4200:8080"
    volumes:
      - ./logs/frontend:/var/log/nginx
    labels:
      service-role: "frontend"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
