name: Test Build

on:
  push:
    branches:
      - infra

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Angular image
        run: docker build -f conduit-frontend/frontend.Dockerfile -t my-angular-app ./conduit-frontend

      - name: Build Django image
        run: docker build -f conduit-backend/backend.Dockerfile -t my-django-app ./conduit-backend
